version: '3.4'

services:
  exchangerate.api:
    image: ${DOCKER_REGISTRY-}exchangerateapi
    build:
      context: .
      dockerfile: src/ExchangeRate.Api/Dockerfile
    depends_on:
      - seq
      - sqlserver
      - redis
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sqlserver
    environment:
      SA_PASSWORD: "P@ssWord123!"
      ACCEPT_EULA: "Y"
    ports:
      - "4444:1433"
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - REDIS_PASSWORD=password123
    ports:
    - '7000:6379'
